import os
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT


def get_supabase_databases():
    databases = {}
    for key, value in os.environ.items():
        if key.startswith("SUPABASE_DATABASE_"):
            databases[key] = value
    return databases


def create_table_if_not_exists(conn):
    try:
        cursor = conn.cursor()

        create_table_query = """
        CREATE TABLE IF NOT EXISTS public.cpr_table (
            id int8 GENERATED BY DEFAULT AS IDENTITY(
                INCREMENT BY 1
                MINVALUE 1
                MAXVALUE 9223372036854775807
                START 1
                CACHE 1
                NO CYCLE
            ) NOT NULL,
            created_at timestamptz DEFAULT now() NOT NULL,
            CONSTRAINT cpr_table_pkey PRIMARY KEY (id)
        );
        """

        cursor.execute(create_table_query)
        conn.commit()
        cursor.close()
        print("  ✓ Table cpr_table checked/created successfully")
        return True
    except Exception as e:
        print(f"  ✗ Error creating table: {e}")
        return False


def insert_record(conn):
    try:
        cursor = conn.cursor()

        insert_query = "INSERT INTO public.cpr_table (created_at) VALUES (NOW());"
        cursor.execute(insert_query)
        conn.commit()

        cursor.execute("SELECT COUNT(*) FROM public.cpr_table;")
        count = cursor.fetchone()[0]

        cursor.close()
        print(f"  ✓ Record inserted successfully (Total records: {count})")
        return True
    except Exception as e:
        print(f"  ✗ Error inserting record: {e}")
        return False


def process_database(db_name, db_url):
    print(f"\nProcessing database: {db_name}")
    print(f"  Connection URL: {db_url[:30]}...")

    try:
        conn = psycopg2.connect(db_url)
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)

        if create_table_if_not_exists(conn):
            insert_record(conn)

        conn.close()
        print(f"  ✓ Database {db_name} processed successfully")
        return True
    except Exception as e:
        print(f"  ✗ Error connecting to database {db_name}: {e}")
        return False


def main():
    print("=" * 50)
    print("Supabase CPR - Database Keep-Alive Service")
    print("=" * 50)

    databases = get_supabase_databases()

    if not databases:
        print("\n⚠ No database configurations found!")
        print("Please set environment variables starting with 'SUPABASE_DATABASE_'")
        print("Example: SUPABASE_DATABASE_URL_1=postgresql://...")
        return

    print(f"\nFound {len(databases)} database(s) to process:")
    for db_name in databases.keys():
        print(f"  - {db_name}")

    success_count = 0
    for db_name, db_url in databases.items():
        if process_database(db_name, db_url):
            success_count += 1

    print("\n" + "=" * 50)
    print(f"Summary: {success_count}/{len(databases)} database(s) processed successfully")
    print("=" * 50)


if __name__ == "__main__":
    main()
